/**
 * LAGOS ON CHAIN (LOC) — CURATED REAL-WORLD DATA ENGINE
 * Authentic spots, coordinates, pricing tiers, and on-chain event actions.
 */

const LAGOS_DATA = {
  // Live market parameters
  market: {
    solUsd: 152.40,
    usdcNgn: 1560.00,
    founderFeePercent: 3.5,
    explorerTierLevels: [
      { name: "Cadet Explorer", threshold: 0, perks: "Standard radar access" },
      { name: "Cross-Bridge Nomad", threshold: 3, perks: "5% off partner joints + Free Zobo" },
      { name: "Gidi Alaga (VIP)", threshold: 6, perks: "15% off Street Souk + Superteam Pool Airdrop" }
    ]
  },

  // Curated Spots Database
  spots: [
    {
      id: "spot_korede",
      name: "Korede Spaghetti (Special)",
      category: "under10k",
      subCategory: "pasta",
      zone: "mainland",
      lga: "Akoka, Yaba",
      lat: 6.5185,
      lng: 3.3872,
      priceNgn: 3500,
      priceTier: "₦ Under 5k",
      vibe: "Legendary UNILAG youth staple. Fiery spiced spaghetti with fried turkey and boiled egg.",
      perk: "Show Gidi Pass: Free cold chilled Maltina or Zobo with any order above ₦3,000",
      isSponsored: false,
      questReward: "50 GIDI XP + Akoka Explorer cNFT",
      imageTag: "spaghetti"
    },
    {
      id: "spot_glover_suya",
      name: "Glover Court Suya",
      category: "under10k",
      subCategory: "street",
      zone: "island",
      lga: "Glover Rd, Ikoyi",
      lat: 6.4520,
      lng: 3.4385,
      priceNgn: 6500,
      priceTier: "₦ Under 10k",
      vibe: "The gold standard of Lagos beef suya, masa, and kidney skewers since the 1990s.",
      perk: "Show Gidi Pass: Extra Masa cake + priority fast-line wrapping",
      isSponsored: true,
      questReward: "75 GIDI XP + Ikoyi Suya Master cNFT",
      imageTag: "suya"
    },
    {
      id: "spot_amala_shitta",
      name: "Amala Shitta (Olaiya)",
      category: "under10k",
      subCategory: "amala",
      zone: "mainland",
      lga: "Surulere",
      lat: 6.4975,
      lng: 3.3580,
      priceNgn: 4500,
      priceTier: "₦ Under 5k",
      vibe: "Silky black amala, steaming gbegiri, ewedu, and tender goat meat dripping in spicy buka stew.",
      perk: "Show Gidi Pass: 10% discount when paying with Solana Pay (USDC)",
      isSponsored: false,
      questReward: "60 GIDI XP + Surulere Amala cNFT",
      imageTag: "amala"
    },
    {
      id: "spot_white_house",
      name: "White House Buka",
      category: "under10k",
      subCategory: "amala",
      zone: "mainland",
      lga: "Commercial Ave, Yaba",
      lat: 6.5095,
      lng: 3.3790,
      priceNgn: 4000,
      priceTier: "₦ Under 5k",
      vibe: "The tech-cluster fueling station in Yaba. Frequented by software devs and students alike.",
      perk: "Show Gidi Pass: Free fried plantain (Dodo) add-on",
      isSponsored: false,
      questReward: "50 GIDI XP + Silicon Yaba cNFT",
      imageTag: "rice"
    },
    {
      id: "spot_danfo_bistro",
      name: "Danfo Bistro & Dives",
      category: "under10k",
      subCategory: "pasta",
      zone: "island",
      lga: "Alexander Rd, Ikoyi",
      lat: 6.4565,
      lng: 3.4470,
      priceNgn: 9500,
      priceTier: "₦ Under 10k",
      vibe: "Lagos street culture meets retro diner. Danfo burger sliders, yam fries, and chill music.",
      perk: "Show Gidi Pass: 15% off mocktails during happy hour",
      isSponsored: true,
      questReward: "80 GIDI XP + Island Vibe Pass",
      imageTag: "burger"
    },
    {
      id: "spot_yellow_chilli",
      name: "Yellow Chilli Grills",
      category: "under10k",
      subCategory: "street",
      zone: "mainland",
      lga: "GRA, Ikeja",
      lat: 6.5910,
      lng: 3.3555,
      priceNgn: 8500,
      priceTier: "₦ Under 10k",
      vibe: "Spicy jollof fiesta, seafood okra, and peppered snails in the heart of Ikeja.",
      perk: "Show Gidi Pass: Free Chapman cocktail with any main course",
      isSponsored: false,
      questReward: "65 GIDI XP + Mainland Core cNFT",
      imageTag: "grill"
    },
    {
      id: "spot_nike_art",
      name: "Nike Art Gallery & Cultural Hub",
      category: "culture",
      subCategory: "art",
      zone: "island",
      lga: "Elegushi Beach Rd, Lekki",
      lat: 6.4350,
      lng: 3.4880,
      priceNgn: 3000,
      priceTier: "₦ Free / Under 5k",
      vibe: "Five soaring floors containing over 25,000 African masterpieces. Pure Lagos creative heritage.",
      perk: "Show Gidi Pass: Free guided tour of textile and bronze collections",
      isSponsored: true,
      questReward: "100 GIDI XP + Nike Heritage cNFT",
      imageTag: "art"
    },
    {
      id: "spot_freedom_park",
      name: "Freedom Park (Old Broad St Prison)",
      category: "culture",
      subCategory: "music",
      zone: "island",
      lga: "Lagos Island / CMS",
      lat: 6.4510,
      lng: 3.3980,
      priceNgn: 1500,
      priceTier: "₦ Under 5k",
      vibe: "Colonial prison transformed into a lush sanctuary for live Afrobeat, indie theater, and palm wine.",
      perk: "Show Gidi Pass: Express entry bypass at weekend festivals",
      isSponsored: false,
      questReward: "70 GIDI XP + Lagos History cNFT",
      imageTag: "park"
    },
    {
      id: "spot_afrika_shrine",
      name: "The New Afrika Shrine",
      category: "culture",
      subCategory: "music",
      zone: "mainland",
      lga: "Agidingbi, Ikeja",
      lat: 6.6180,
      lng: 3.3540,
      priceNgn: 2000,
      priceTier: "₦ Under 5k",
      vibe: "The immortal temple of Fela Kuti and Afrobeat. Raw, hypnotic brass horns and authentic energy.",
      perk: "Show Gidi Pass: Shrine Explorer Badge + 10% off merch",
      isSponsored: false,
      questReward: "90 GIDI XP + Kalakuta Spirit cNFT",
      imageTag: "shrine"
    },
    {
      id: "spot_bogobiri",
      name: "Bogobiri House Live Lounge",
      category: "culture",
      subCategory: "music",
      zone: "island",
      lga: "Maitama Sule, Ikoyi",
      lat: 6.4490,
      lng: 3.4240,
      priceNgn: 9000,
      priceTier: "₦ Under 10k",
      vibe: "Intimate bamboo bar, spoken-word poetry, highlife bands, and vintage African furniture.",
      perk: "Show Gidi Pass: Free craft palm-wine shot on arrival",
      isSponsored: false,
      questReward: "75 GIDI XP + Bohemian Gidi cNFT",
      imageTag: "lounge"
    }
  ],

  // Upcoming Underground Events (Solana Blinks Integration)
  events: [
    {
      id: "event_street_souk",
      title: "Street Souk 2026: The Lagos Underground",
      organizer: "Street Souk Community",
      category: "event",
      zone: "island",
      venue: "Harbour Point, Victoria Island",
      lat: 6.4320,
      lng: 3.4250,
      date: "Saturday, Oct 24 • 12:00 PM",
      desc: "Africa's biggest streetwear, sneaker, and music convention. Exclusive local designer drops, skate demos, and secret DJ sets.",
      priceSol: 0.08,
      priceUsdc: 12.00,
      priceNgn: 18500,
      ticketsLeft: 142,
      blinkActionUrl: "solana-action:https://lagosonchain.xyz/api/actions/streetsouk-pass",
      highlights: ["No POS network failures", "Anti-scalp cNFT ticket", "Exclusive Merch Airdrop"],
      bannerColor: "linear-gradient(135deg, #FF3B5C 0%, #9945FF 100%)"
    },
    {
      id: "event_stiim_vault",
      title: "STIIM: Secret Warehouse Rave Vol. 4",
      organizer: "STIIM Collective",
      category: "event",
      zone: "island",
      venue: "Industrial Depot, Lekki Phase 1",
      lat: 6.4410,
      lng: 3.4680,
      date: "Friday, Nov 06 • 10:00 PM - Dawn",
      desc: "High-octane electronic Afro-house, UK bass, and amapiano inside an abandoned warehouse. BYOB until 2 AM.",
      priceSol: 0.05,
      priceUsdc: 7.50,
      priceNgn: 11500,
      ticketsLeft: 64,
      blinkActionUrl: "solana-action:https://lagosonchain.xyz/api/actions/stiim-rave",
      highlights: ["Proof-of-Entry cNFT", "Secret location revealed 3h before", "Direct DJ tip jar"],
      bannerColor: "linear-gradient(135deg, #14F195 0%, #00F0FF 100%)"
    },
    {
      id: "event_mainland_blockparty",
      title: "Mainland BlockParty: Festac Edition",
      organizer: "BlockParty Series",
      category: "event",
      zone: "mainland",
      venue: "FESTAC Ground, Amuwo Odofin",
      lat: 6.4680,
      lng: 3.2840,
      date: "Sunday, Nov 15 • 3:00 PM",
      desc: "The undisputed energy capital of youth partying. High-voltage dance battles, live rap cyphers, and unlimited suya grills.",
      priceSol: 0.04,
      priceUsdc: 6.00,
      priceNgn: 9500,
      ticketsLeft: 310,
      blinkActionUrl: "solana-action:https://lagosonchain.xyz/api/actions/mainland-blockparty",
      highlights: ["Under 10k Entry", "Blink 1-Click RSVP", "Solana Pay drink bar"],
      bannerColor: "linear-gradient(135deg, #FF8A00 0%, #FF3B5C 100%)"
    },
    {
      id: "event_skate_jam",
      title: "Gidi Skate & Street Cypher",
      organizer: "WAFFLESNCREAM & Friends",
      category: "event",
      zone: "mainland",
      venue: "National Stadium Concourse, Surulere",
      lat: 6.4990,
      lng: 3.3640,
      date: "Saturday, Nov 21 • 1:00 PM",
      desc: "Skateboard best-trick contest, live graffiti mural sessions, and hip-hop open mic. Free admission with PoPV check-in.",
      priceSol: 0.02,
      priceUsdc: 3.00,
      priceNgn: 4500,
      ticketsLeft: 88,
      blinkActionUrl: "solana-action:https://lagosonchain.xyz/api/actions/gidi-skate",
      highlights: ["Free deck raffle for check-ins", "cNFT attendee badge", "Live cyphers"],
      bannerColor: "linear-gradient(135deg, #9945FF 0%, #14F195 100%)"
    }
  ]
};

// Expose to window
window.LAGOS_DATA = LAGOS_DATA;
